### ISSUE TITLE
Multiplayers save

### ISSUE THREAD

**Issue by aerao** [KingEnderBrine/-RoR2-ProperSave#1]
Hello, I know that the version is intended for a single player, but is the multiplayer version possible to code? Are you planning to create a version for this? If it is feasible of course.
Thx!

**Comment by KingEnderBrine** [comment]
Hello, yes when I will have more time, I will work on multiplayer support.

**Comment by aerao** [comment]
Greats!
We are 3-4 players and we play almost every day.
if you need to have testers, we can help.

**Comment by KingEnderBrine** [comment]
@aerao Multiplayer support update is now published on thunderstore, so check it out.

**Comment by aerao** [comment]
Great, I'm going to test this with my friends tonight, we're going to take as many different items as possible to do the tests. Thank you again, I say you if everything is OK

**Comment by aerao** [comment]
Great, i will test this with my friends tonight! if I find a bug, I will tell you. thank you!
