### ISSUE TITLE
Seems to crash the 1.0 menu

### ISSUE THREAD

**Issue by LavenderTheGreat** [KingEnderBrine/-RoR2-ProperSave#11]
Mainly getting the following after installing it:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.UI.MainMenu.MainMenuController.Update () (at <0ea3156211b84bca85ad16490410c2a9>:0)
```
Sadly I don't have anymore info on the issue. It's worth noting I was also running TooManyFriends

**Comment by bartkloostra** [comment]
![Inkedb3caed534c1a3cd8440928e46f688f97_LI](https://user-images.githubusercontent.com/33312781/90189660-d5939d80-ddbd-11ea-8fca-1f85383efdb0.jpg)

Same problem here. This is what i see before getting the error stated by LavenderTheGreat. I'm using the most recent versions of BepInExPack and R2API (as of now). And I'm only using ProperSave.

**Comment by KingEnderBrine** [comment]
Hello, I know about this issue, and I've started fixing it. But I can't do that before a stable version of R2API is released.

**Comment by nikil07** [comment]
Hey man,
Thank you so much for the mod..

I literally downloaded Risk of Rain just cos this mod exists.

Will be waiting for a fix before I get into playing the game, dont want to exceed the refund window. 
Without this mod, Risk of Rain is not a product for me.

Cheers. All the best.

**Comment by KingEnderBrine** [comment]
I have updated the mod for the game release. The issue is solved
