### ISSUE TITLE
Sorry to ask this here. Need help in using the mod

### ISSUE THREAD

**Issue by nikil07** [KingEnderBrine/-RoR2-ProperSave#13]
Hey,

So I went into stage 2, and then exited the game. 
I clicked "end the run" to exit. Is that wrong?

How do I make the mod to save/load?

Thank you,
Nikhil

**Comment by KingEnderBrine** [comment]
Save is happening automatically at the start of the stage. You will see a message in chat about game being saved. To load saved game you enter the lobby and click `Load` button (bottom right corner).

**Comment by nikil07** [comment]
Does the load work even if I clicked "end the run" when exiting?
