### ISSUE TITLE
Can load saves after beating game

### ISSUE THREAD

**Issue by MissPotato** [KingEnderBrine/-RoR2-ProperSave#17]
When beating Mithrix I noticed that my load button was still there. Clicking it took me to the end sequence animation. This is mostly fine but it caused all my drones to spawn in the next run with no AI.

**Comment by KingEnderBrine** [comment]
Hello, I've beaten Mithrix and the button is inactive. Can you recreate that and paste a log file?

**Comment by MissPotato** [comment]
I'm guessing if you can not reproduce the issue, it's probably a mod conflict. I'll narrow down what mods are required to recreate this and get back to you!

**Comment by MissPotato** [comment]
Okay, so it seems that you actually have to restart the game for this bug to happen, I was able to reproduce it with just Proper Save, BepinExPack, and R2API. 

The exact steps I've done are:
1) Disable all mods but those three.
2) Get to the moon.
3) Quit to menu, load save. (I do not know if this is a required step as I had done it to back up the save for testing)
4) Beat Mithrix and finish the escaping sequence. 
5) Skip cutsceen, skip credits, hit continue.
6) Quit out of the game once you're at the character select.
7) Reboot game, select single player, load button is now select-able with broken save. 


Loading this save will play the first cut scene but will throw an NRE when it trys to choose the post-game character flavor text. This results in black screen that wont advance, but you can still pause and quit to menu. This will cause weird behaviors in the next run such as the game spawning drones bought in the broken save file with no AI equivalent to stage number. (Stage one will have one drone spawn with you with no ai, stage two will have two drones with no ai, etc)

**Comment by KingEnderBrine** [comment]
I would never found that. Thanks for reporting about that issue. The update is out.
