### ISSUE TITLE
Accidental "The Long Road" achievement unlock

### ISSUE THREAD

**Issue by popcar2** [KingEnderBrine/-RoR2-ProperSave#18]
When hosting a server with propersave with my friends that don't own the mod, as soon as we reached stage 2 both of them unlocked "The Long Road" achievement (complete 20 stages in one run). This probably happened because clients couldn't keep track of the stage number.

**Comment by KingEnderBrine** [comment]
Hello, this happened after you loaded the game, or is it was a new run?

**Comment by popcar2** [comment]
This was a new run. I didn't load anything that time. As soon as we moved
to stage 2 the achievement unlocked.

**Comment by KingEnderBrine** [comment]
Then a problem is not caused by `ProperSave`. Because it doesn't do anything to a new run except saving, which is not causing any values to change. And I've just tested it in multiplayer with a vanilla version and modded with only `ProperSave` and no achievement.
