### ISSUE TITLE
mithrix and monsters?

### ISSUE THREAD

**Issue by lejug3** [KingEnderBrine/-RoR2-ProperSave#25]
will there be fix scripts for mithrix and other monsters from the game?

**Comment by KingEnderBrine** [comment]
First of all, why open an issue here and not in the corresponding [repository](https://github.com/KingEnderBrine/-RoR2-BlenderScripts). Second, I don't have much time and will to do monsters, especially because scripts main purpose of those scripts are for skins for characters

**Comment by lejug3** [comment]
i'm sorry, i'm new to github. i made this account just to ask for this, and i'm not very familliar with stuff.
