### ISSUE TITLE
Where are save files located?

### ISSUE THREAD

**Issue by Rings4** [KingEnderBrine/-RoR2-ProperSave#26]
Sorry for asking this here, don't know where else to ask. I was just wondering where the save files are stored? 
Thanks in advance!

**Comment by KingEnderBrine** [comment]
AppData\LocalLow\Hopoo Games, LLC\Risk of Rain 2\ProperSave

**Comment by Rings4** [comment]
> 
> 
> AppData\LocalLow\Hopoo Games, LLC\Risk of Rain 2\ProperSave

Thanks so much!
