### ISSUE TITLE
Confirm Dialog Text

### ISSUE THREAD

**Issue by maxwellainatchi** [KingEnderBrine/-RoR2-ProperSave#27]
When you leave the game, and it says "Are you sure you want to end this run?", it would be nice if the mod added a `Last saved: 5s ago" or something... I get a little paranoid that I forgot to enable the mod sometimes, and want to know if I'm ending the run or if I'm safe to continue later.

Favorite RoR2 mod by the way, thanks for this!

**Comment by KingEnderBrine** [comment]
There is actually a message in a chat at the start of each stage if the game was saved, though it's kinda hard to distinguish to which stage it's corresponding since it's the same message every time. I will think about that.

**Comment by KingEnderBrine** [comment]
The update is up. Added text to a quit confirmation dialog which tells you if the game was saved on the current stage, saved n stage ago, or not saved at all.

**Comment by maxwellainatchi** [comment]
Thanks!!
