### ISSUE TITLE
How to personally edit mods to work with save

### ISSUE THREAD

**Issue by cory-eheart-1** [KingEnderBrine/-RoR2-ProperSave#29]
My friend and I have been playing together, and we noticed the series of Dragonball mods do not save progress with their levels. Can I modify those files myself to work with ProperSave?

**Comment by KingEnderBrine** [comment]
Technically, yes, not sure about the amount of work you would have to do.

**Comment by cory-eheart-1** [comment]
Thanks. I'll try to contact the mod creators.

**Comment by KingEnderBrine** [comment]
Well, it will be much easier for the mod creator.

**Comment by cory-eheart-1** [comment]
I tried contacting the mod creator and they seem to be opposed to fixing the issue globally. Is there anyway I could contact you directly to talk about modifying the code myself? I am a bit inexperienced with RoR2 modding, and your knowledge would be useful.

**Comment by KingEnderBrine** [comment]
My discord is KingEnderBrine#3624

**Comment by cory-eheart-1** [comment]
Thank you. I am DirtyDeedsDoneDirtCheap
