### ISSUE TITLE
Update to use Application.persistantDataPath instead of Executing directory

### ISSUE THREAD

**Issue by PassivePicasso** [KingEnderBrine/-RoR2-ProperSave#3]
this will prevent users from accidentally deleting their saves if they have to redo their modding installations or re-install ror2.

https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html

**Comment by PassivePicasso** [comment]
update this line:
https://github.com/KingEnderBrine/-RoR2-ProperSave/blob/develop/ProperSave/ProperSave.cs#L39

**Comment by PassivePicasso** [comment]
Propose fix is untested.

**Comment by PassivePicasso** [comment]
It would probably be ideal to silently move users saves from the current dir to the new dir.

**Comment by KingEnderBrine** [comment]
Hello, thanks for proposed fix. I will add it in the next update.
