### ISSUE TITLE
Newest update not working

### ISSUE THREAD

**Issue by MichelJonkman** [KingEnderBrine/-RoR2-ProperSave#30]
As kind of expected, the new update breaks the mod.

**Comment by KingEnderBrine** [comment]
It's not only this mod. Most of the mods are broken and the most important is r2api. I need to wait for the r2api update to fix my mods.

**Comment by ScriptingShogun** [comment]
I can see on thunderstore the mod has been marked as deprecated (https://thunderstore.io/package/KingEnderBrine/ProperSave/). I just wanted to check here to confirm if there is no plan to update the mod.

**Comment by KingEnderBrine** [comment]
I will update the mod. Deprecation doesn't necessarily mean there will be no updates, it means the mod doesn't work.

**Comment by KingEnderBrine** [comment]
Published an update.
