### ISSUE TITLE
Do you take donations?

### ISSUE THREAD

**Issue by ScriptingShogun** [KingEnderBrine/-RoR2-ProperSave#31]
This is by far my favorite mod as it actually allows me to play the game in small chunks. I just wanted to know if there is a way to send you a donation as thanks :)

**Comment by KingEnderBrine** [comment]
Thank you. No, currently there is no way for that. Maybe I will set up something for that in the future.

**Comment by KingEnderBrine** [comment]
Did set up a donation page: https://www.buymeacoffee.com/KingEnderBrine
