### ISSUE TITLE
Does this not work anymore?

### ISSUE THREAD

**Issue by thegr8anand** [KingEnderBrine/-RoR2-ProperSave#35]
I installed the mod and after changing level i quit to play later. But i see no option to continue my save.

**Comment by KingEnderBrine** [comment]
It does work. Start a run, complete 1 stage, exit the game, and then send log file, so I would have some info to be able to help you. To get log you can follow these instructions from ror2 modding discord

If you are using r2modman or Thunderstore Mod Manager:
You can copy your log by going to the Settings screen, selecting the Debugging tab and clicking Copy LogOutput.log to clipboard

If you have manual install:
You can find such log file in your Risk of Rain 2/BepInEx/ folder, the file is called LogOutput.log.

**Comment by thegr8anand** [comment]
Sorry. It is working now when i tried it. I get a save message before quitting and i can load. Thank you for this great mod.
