### ISSUE TITLE
DLC - Survivors of the VOID

### ISSUE THREAD

**Issue by RussInSA** [KingEnderBrine/-RoR2-ProperSave#37]
Not exactly sure if the issue is the MMHOOK library but ProperSave no longer works with latest Risk of Rain 2 Update, whether you have the DLC purchased/installed or not.

When you to to create a new game, it gives a LOAD button, regardless of whether there's a valid load/proper players or not.  In addition, it's not longer writing a SavesMetadata.json file or a serialized .json game file.

**Comment by KingEnderBrine** [comment]
Answered it here: https://github.com/KingEnderBrine/-RoR2-ProperSave/issues/32#issuecomment-1062505472

**Comment by RussInSA** [comment]
Thank you SO much, it’s by far my favorite mod because I play only multiplayer with my buddy who sometimes gets disconnected to unstable internet service.

Thanks!!!!

**Comment by KingEnderBrine** [comment]
Published an update
