### ISSUE TITLE
Missing exit button

### ISSUE THREAD

**Issue by SirHanus** [KingEnderBrine/-RoR2-ProperSave#38]
I may be missing something but when I try this mod, I cant quite game.

![image](https://user-images.githubusercontent.com/57251061/157679847-808bea09-4580-4817-ac0d-407a10206397.png)

![image](https://user-images.githubusercontent.com/57251061/157680211-4fd413c5-b32f-46cf-989e-2e8bb3ba4ff6.png)

After a while the game crashes and after starting it again the Load button is there but does nothing.

I tried digging in the code but couldn't seemed to figure out what is happening since I never wrote mods for this game.

Could you tell me what I do wrong?

**Comment by KingEnderBrine** [comment]
The only thing you doing wrong is trying to use broken mod. There was update 1.5 weeks ago which broke almost all mods. I'm slowly fixing my mods, but there's still a lot to do

**Comment by SirHanus** [comment]
Ouh thanks. I didn't know. Just bought the game because my proffesor suggested that it is good for modding.

Then good luck with the fixes.

**Comment by KingEnderBrine** [comment]
Published an update
