### ISSUE TITLE
Loading saves causes chest price to reset.

### ISSUE THREAD

**Issue by The-Register** [KingEnderBrine/-RoR2-ProperSave#39]
Was reloading a save onto sky meadows last night when I realized that all of the chest prices were reverted back to stage 1 pricing (Regular chests = 25, Large chests = 50, etc...) the prices reverted to their proper pricings after leaving the affected stage. I finished out my run and did some testing.

![image](https://user-images.githubusercontent.com/101779641/158855320-c09c74df-0015-4821-94d2-d20f4d509f9b.png)
_My first encounter with the bug_

I started working on reproducing the bug to see if I can see what caused it:
Started new run
Progressed to stage 2
Confirmed current chest price (i.e $60 chest)
![image](https://user-images.githubusercontent.com/101779641/158857771-6a3e69ee-d387-425f-9b21-2441dd990513.png)
_$64 utility chest_
Quit to desktop 
Reloaded the save
rechecked the current price of the chest
![image](https://user-images.githubusercontent.com/101779641/158858108-a0f33638-02e0-4c00-9934-7492b9885b12.png)
_back down to 30 after reload_
repeat except I quit to the menu instead

What I seemed to learn was "quit to desktop" caused the bug while "quit to menu" did not. that said if you reload a stage where the bug occurs quitting to the main menu and reloading will fix the prices again

Ultimately it's rather minor but still worth reporting, I feel.

**Comment by KingEnderBrine** [comment]
Thanks for the report, really weird issue, published an update with a fix
