### ISSUE TITLE
Simulacrum doesnt load on multiplayer

### ISSUE THREAD

**Issue by arthiccc** [KingEnderBrine/-RoR2-ProperSave#41]
Simulacrum doesnt load

**Comment by KingEnderBrine** [comment]
Send a log

**Comment by arthiccc** [comment]
[LogOutput.log](https://github.com/KingEnderBrine/-RoR2-ProperSave/files/8379734/LogOutput.log)

**Comment by KingEnderBrine** [comment]
Buy the game first, can't tech-support pirate version
