### ISSUE TITLE
Certain other mods' Russian tokens don't get loaded when this mod is active

### ISSUE THREAD

**Issue by TheMysticSword** [KingEnderBrine/-RoR2-ProperSave#46]
I don't know the exact reason, but I know that if you rename the `ru` folder to something, and then back to `RU` in caps, the problem gets fixed.
Examples of mods that are affected by this are MysticsItems and ImprovedRussianTranslation.
(Same issue happens with InLobbyConfig)

**Comment by KingEnderBrine** [comment]
It was an issue with R2API, created PR with a fix for it https://github.com/risk-of-thunder/R2API/pull/402
