### ISSUE TITLE
Unable to locate Loading function for Alternative Game Modes

### ISSUE THREAD

**Issue by githubplanetarparrot** [KingEnderBrine/-RoR2-ProperSave#48]
Hello,

I just have a question about where the load buttons would be with the new alternative game modes. I was able to confirm I have a save file, but am unable to load is for Simulacrum. Loading works fine for standard single player, but not alternative game modes. What is the load button supposed to look like for alternative game modes? Are there any known compatibility issues with this mod; I can provide my mod list if needed?

Thanks.  

![image](https://user-images.githubusercontent.com/10856801/181866289-650e7825-a8b6-443e-8c89-8d3d96dd4f8b.png)

![image](https://user-images.githubusercontent.com/10856801/181866299-3d78db0b-8607-41db-bd4c-3363e478898e.png)

And a screenshot of my save in Windows File Explorer for Simulacrum. 

![image](https://user-images.githubusercontent.com/10856801/181866328-a519c524-1f17-4b2f-bae6-510e7678486f.png)

**Comment by KingEnderBrine** [comment]
When you click `Execute` in Simulacrum screen, you get into lobby, the button is there, in the same place it's in normal game
