### ISSUE TITLE
Where to download and how to install?

### ISSUE THREAD

**Issue by magical-heyrovsky** [KingEnderBrine/-RoR2-ProperSave#49]
Some guidelines in the README regarding where to download and how to install this mod would be great. Because I have no idea how to do either. Do I have to compile and build it myself? The [releases](https://github.com/KingEnderBrine/-RoR2-ProperSave/releases) only contain the source code.

**Comment by KingEnderBrine** [comment]
The compiled mod is on https://thunderstore.io/package/KingEnderBrine/ProperSave/, you can use mod managers to install it and any other mod from the site
