### ISSUE TITLE
Equipment drones fire too frequently after loading a save

### ISSUE THREAD

**Issue by 6thmoon** [KingEnderBrine/-RoR2-ProperSave#50]
Upon loading a save it looks like *Equipment Drones* are being granted extra copies of the `BoostEquipmentRecharge` item that they always carry. This can get pretty out of hand across subsequent reloads, to the point where low cooldown equipment like **Royal Capacitor** fire multiple times per second.

**Comment by KingEnderBrine** [comment]
Thank you for the report! The issue should now be fixed
