### ISSUE TITLE
Inventory disappears on load after crash

### ISSUE THREAD

**Issue by EquinoxRevolt** [KingEnderBrine/-RoR2-ProperSave#52]
This issue only seems to happen when the game crashes, (which happen frequently mind you) this has happened a few times and out of all the times it has happened, only once have I not lost my items. So I'm wondering if anyone else has this issue as well. I don't know what causes all of my items to disappear nor what I can do to prevent it from happening but when the game crashes it is seemingly guaranteed for me to lose my entire inventory and thrown into a 120 hour save run and left absolutely helpless. To be fair my only good guess on why this happens is from the extreme amount of mods I have, which I will list in case that is handy. 
Hopefully this issue can be fixed as I'm tired of having to make a new run because I lost all of my items by a inevitable crash.
(alphabetical order besides API's)
 TILER2 by ThinkInvis

VoidItemAPI by RumblingJOSEPH

MysticsRisky2Utils by TheMysticSword

MoonstormSharedUtils by TeamMoonstorm

Risk_Of_Options by Rune580

AI_Blacklist by Moffein

1nsiderItems by 1nsider

AbsaArtificer by AntlerShed

Actually_Faster by Felda

Admiral by ThinkInvis

Aetherium by KomradeSpectre

BalancedObliterateRedux by Nebby

BazaarExpand by NetherCrowCSOLYOO

BazaarPrinter by MagnusMagnuson

BetterUI by XoXFaby

BetterDrones by pseudopulse

BiggerBazaar by MagnusMagnuson

BubbetsItems by Bubbet

Bosses_Drop_Items by Moffein

ChensHelpers by Chen

ChensMineLimitChanger by Chen

ClassicItems by ThinkInvis

DekuMod by TeaL

DiscordRichPresence by Cuno

DropinMultiplayer by niwith

EmptyChestsBeGone by TheRealElysium

EnemiesSpawnFaster by pheintz

Enforcer by EnforcerGang

ExtraSkillSlots by KingEnderBrine

GoldenCoastPlus by Skell

Hex3Mod by hex3

HuntressAutoaimFix by HIFU

HIFUEngineerTweaks by HIFU

HIFUHuntressTweaks by HIFU

Inferno by HIFU

ItemExchangeNotifier by MagnusMagnuson

KookehsDropItem_BepInEx by tristanmcpherson

LobbySkinsFix by KingEnderBrine

LTGCapacitor by Thalassophobia

MicroDropBots by arimah

MobileTurretBuff by Moffein

More_Difficulties by SpikestripModding

Multitudes by wildbook

MysticsItems by TheMysticSword

 NoBossNoWait by mistername

OriginalSoundTrack by Contraplayingmodded

PaladinMod by Paladin_Alliance

ProperSave by KingEnderBrine

QuickRestart by AceOfShades

Raise_Monster_Level_Cap by Moffein

RiskOfWaiting by Groove_Salad

ScrollableLobbyUI by KingEnderBrine

ShowDeathCause by NotTsunami

StandaloneAncientScepter by amogus_lovers

Starstorm2 by TeamMoonstorm

Synced_Turrets by WPhantom

Synergies by Dragonyck

TeleporterShowRedux by Pipman3000

TinkersSatchel by ThinkInvis

VanillaVoid by Zenithrium

Voice_Acted_Mithrix by Heyimnoob

WhatAmILookingAt by Bubbet

(MORE API'S BELOW)

R2API_ArtifactCode by RiskofThunder

R2API_CommandHelper by RiskofThunder

R2API_ContentManagement by RiskofThunder

R2API_DamageType by RiskofThunder

R2API_Deployable by RiskofThunder

R2API_Difficulty by RiskofThunder

R2API_Director by RiskofThunder

R2API_Dot by RiskofThunder

R2API_Elites by RiskofThunder

R2API_Items by RiskofThunder

R2API_Language by RiskofThunder

R2API_Loadout by RiskofThunder

R2API_LobbyConfig by RiskofThunder

R2API_Networking by RiskofThunder

R2API_Orb by RiskofThunder

R2API_Colors by RiskofThunder

R2API_Prefab by RiskofThunder

R2API_RecalculateStats by RiskofThunder

R2API_SceneAsset by RiskofThunder

R2API_Sound by RiskofThunder

R2API_TempVisualEffect by RiskofThunder

R2API_Unlockable by RiskofThunder

R2API_Core by RiskofThunder

R2API by tristanmcpherson

Normally I would solve this myself but I have no clue where to start and have to pray someone can fix this easily and that I might just be really stupid.

**Comment by KingEnderBrine** [comment]
Hello, there is no difference between exiting the game normally and crashing in terms of loading save. Can you send a log? And better would be sending 2, one right after the crash and one after you loaded the game and your inventory has dissapeared

**Comment by EquinoxRevolt** [comment]
Sorry, I'm having some technical difficulty's on my side, and I'm catching up with life it may be a bit before I can get the logs to you.

**Comment by EquinoxRevolt** [comment]
The issue has seemed to stop for now, I have been testing it nearly everyday and it seems not to delete my inventory on crash. I will be keeping track every crash and come back to this issue if it happens again.
