### ISSUE TITLE
Lag when opening chests after loading a save

### ISSUE THREAD

**Issue by breadguyyy** [KingEnderBrine/-RoR2-ProperSave#53]
May or may not be related to executive card money refund, but almost certainly related to Pathfinder's Squall ally

[zipped_log.zip](https://github.com/KingEnderBrine/-RoR2-ProperSave/files/10809473/zipped_log.zip)

**Comment by KingEnderBrine** [comment]
Oops, left some unnecessary logging when minions inventory change after loading while fixing extra items after loading, which with your mod list printed 125 lines long message each time minion had inventory changed. Should be fixed now

**Comment by breadguyyy** [comment]
Nice, thank you
