### ISSUE TITLE
Save point change in case of PC shut down

### ISSUE THREAD

**Issue by Portur** [KingEnderBrine/-RoR2-ProperSave#54]
Hi there.

I live in a country where we regularly have power outages. We only have 4 hours of electricity at any given time and since its difficult to use that time to only play RoR2 and not make food, wash clothes, etc... this means this save mod makes RoR2 playable, in theory.

At the moment the save only happens on menu exit from the game, not when the game closes abruptly or when power is lost to the machine.

Is it possible to make the save happen when the stage starts and not when the run is exited to menu?

**Comment by Portur** [comment]
Or is there a different reason why the save isn't available once RoR2 is started up again after a power failure?

**Comment by KingEnderBrine** [comment]
The game is saved at the start of the stage, not when you exit it, so, even if the game crashed/your power went out, the game was already saved
