### ISSUE TITLE
Question: Is it possible if one want to change the current default save location of ProperSave mod for ror2 game save file?

### ISSUE THREAD

**Issue by KaitoXion** [KingEnderBrine/-RoR2-ProperSave#56]
As per title, would it be possible for one to write a .cfg file that could change the saving location of the ProperSave saving location?
I couldn't find any .cfg file being generated in BepInEx\config folder, and I think am noop at this, so I don't know if merely creating a .cfg with the mod name can actually change anything.

Current save location: AppData\LocalLow\Hopoo Games, LLC\Risk of Rain 2\ProperSave\
New save location due to limitation: "in the same folder as the ROR 2 game folder" or at the same drive as where the game is being stored.

My apology for the inconvenience. Should you think this is too annoying to bother with, is cool my question is being ignored.

**Comment by KingEnderBrine** [comment]
Hi. I somewhat forgot about this issue until yesterday when there was another one for this mod. But I added a config option to change saves directory.

**Comment by KaitoXion** [comment]
Thanks.

It helps a lot. Thank you very much for your kind consideration.
I'll use the mod when I had the time later to set everything up again.
Thank you so much.
