### ISSUE TITLE
Loading saves between devices?

### ISSUE THREAD

**Issue by ashkeplussen** [KingEnderBrine/-RoR2-ProperSave#57]
I've been trying to find a way to transfer and load saves between devices via cloud storage and symlinks, but to mostly no success.
In particular, I'm trying to create a save on my PC and load it on my Steam Deck, and vice versa. I've also tried this between two normal PC's.

The problem is that the file names that are read and written to appear to be different between devices, making the process pretty difficult. I would essentially have to create a symlink for each profile, for each gamemode.

Is there any way this process could be made easier?

**Comment by KingEnderBrine** [comment]
Hi, now there is. Just added config to enable using Steam/Epic cloud storage.
