### ISSUE TITLE
Request/Suggestions : saving ability enhancement for new community made Mod Character support (Current discussion: Myst)

### ISSUE THREAD

**Issue by KaitoXion** [KingEnderBrine/-RoR2-ProperSave#58]
Hi,
Disclaimer:
This is a suggestion or request or something like a information. Whether is seem as something to be implemented or not is solely based on the intention of propersave mod creator. As this features are pretty much additional and is not part of the actual support for the original game.

Let's begin, currently the mod is at vers 2.9.0 if I'm not mistaken. Currently the mod works perfectly and allow redefine save file location etc.

What current mod is unable to do is saving something that applies to totally custom-made character. **For current suggestion, support for Myst skill number 3 and 4, and/or inclusion of the skill screen after pressing of number '4' keyboard.**
At this current moment, skill 3 and 4 is not save. Thus it will act as expected, loading up with no skill even if previously have acquired any skill.

This is just an suggestion/information for thought.
Think it may be too annoying to implement, or save file might end up saving something that is not needed.
Might even effect someone that do not have Myst character mode to save something unnecessary into their save file. Unneeded amount of save data size probably is not everyone favorite.

This, this is only something for thought. Thank you for taking your time for reading. (⁠/⁠･⁠ω⁠･⁠(⁠-⁠ω⁠-⁠)

**Comment by KingEnderBrine** [comment]
Hi, ProperSave itself will be only supporting vanilla. However it has public events that other mods can use to save/load whatever info they need, everything is described in the readme. This can be done by the character mod itself, or even a separate mod.

**Comment by KaitoXion** [comment]
While I do not fully underatanda cause Myst happens to have 8 slots for skill 3 and 4.

I think what you meant is that -> ProperSave support the default or vanilla original code and characters only.
Custom Mod character developer can use the given features or methods/code to save and load the needed data for the specific Custom Mod Character.

Noted, I'll inform them if there is a way to contact them.
Thank you very much for your kind words. o⁠(⁠(⁠*⁠^⁠▽⁠^⁠*⁠)⁠)⁠o
