### ISSUE TITLE
After loading a save the next teleporter you use will send you to a stage 1 stage.

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [KingEnderBrine/-RoR2-ProperSave#59]
After loading a save using the teleporter will send me to one of the possible stage 1 stages. Such as Titanic Plains but it is random which one it sends me to. If I continue playing stage 1 and use the teleporter I will be sent to a stage 2 stage and so on, as normal.

But if I interact with a portal or the primordial teleporter it does send me to the correct stage. So it seems to only effect normal teleporters. Though when using the return portal such as the blue portal in the Bazaar, it will then send me to a stage 1 variant.

It seems like it is losing track of the next stage it is meant to send you to and defaulting to stage 1. Or that when loading it is treating the level you load into like a stage 0 or something. 

I am not sure if this is just a me problem, such as if a mod is causing ProperSave to get confused.

Steps to reproduce: 
1. Move to any stage so that propersave, saves a file.
2. Quit the run doesn't matter if it is to menu or desktop.
3. Load the run.
4. Play through the level to be able to move on. Easiest in Void Fields or Bazaar as you can instantly leave.
5. See that the game has loaded one of the stage 1 stages instead of the correct stage.

As a side note this is also visible by visiting the Bazaar after loading. As the dream seers will show stage 1 stages.

**Comment by KingEnderBrine** [comment]
What other mods you have? It isn't a problem for anyone else, so I would guess something is conflicting. You can send your tmm/r2modman profile (as file, the code most likely will expire by the time I see your response)

**Comment by Shiranui-Izayoi** [comment]
> What other mods you have? It isn't a problem for anyone else, so I would guess something is conflicting. You can send your tmm/r2modman profile (as file, the code most likely will expire by the time I see your response)

A fair few I will send it in a bit will remove any skins and stuff. Will try and figure out what the issue is.

**Comment by Shiranui-Izayoi** [comment]
Ok here is the export. I removed any mods that were uninstalled and any skins since I doubt those effect anything. Not sure which one you need since it seemed to make 2 of them.

If I had to guess it MIGHT be StartInBazaar but not 100% sure. 
[Risk Default_1710953023173.zip](https://github.com/KingEnderBrine/-RoR2-ProperSave/files/14669894/Risk.Default_1710953023173.zip)

Let me know if there is anything else that might help. I will try and test to see if I can find the issue as well when I can incase it might save time.

**Comment by KingEnderBrine** [comment]
The issue is with StartInBazaar. Can't fix it on my side.

**Comment by Shiranui-Izayoi** [comment]
Ahhhh ok then I had a vague feeling that that might be the case. I will remove it sorry for bothering you. I will also close the issue.
