### ISSUE TITLE
Captain Supply Drop Bug

### ISSUE THREAD

**Issue by SomeoneWhoUsesGit** [KingEnderBrine/-RoR2-ProperSave#61]
When using captain, if I save and then quit the game both supply drops are used up.
But If i then quit to menu and load back in they are back. 

Thanks

**Comment by KingEnderBrine** [comment]
Should be fixed with latest RoR2BepInExPack update

**Comment by SomeoneWhoUsesGit** [comment]
Can confirm it appears to be fixed now.

Wanted to say I appreciate the mod, thanks.
