### ISSUE TITLE
[Feature Request] Allow loading saves with different mods

### ISSUE THREAD

**Issue by Hlebuw3k** [KingEnderBrine/-RoR2-ProperSave#63]
I have a save that I want to continue playing after removing a mod, but it won't let me do that. When I disable that mod, the load button is not active. It's a mod that adds an alternative game mode, called "Scavanger Bingo" but my save does not use it, so I wanted to get rid of the mod. How can I load my save without that mod, or other mods that are technically "required" to load the save, but didn't affect the save and weren't used in the save? Ideally there would be a save menu with multiple different game saves to choose to load from, but can I do something with the save files to do this?

**Comment by Hlebuw3k** [comment]
Ok, I'm somehow able to load that save anyway, but only in the Eclipse mode menu, and my items are all wrong and bugged out. (I got something called "strange scrap" and some void items and tonic affliction even though I didn't pick up any of this in my run) I'm not sure if this is a bug or an unintended side effect or something, but it's really weird.

**Comment by KingEnderBrine** [comment]
Removing/adding mods is a no-go. Even if you think you don't use whatever you removed it still matters because extra data is still there. Since a mod you removed added a new gamemode it messed with what save file had saved as a gamemode, thus it now identified it as eclipse instead of a normal run.
All you can do is add that mod back and finish the run before changing mod list.

**Comment by Hlebuw3k** [comment]
Thanks for clarifying this. After thinking this over, it actually plays in my favor, since I never use that mod anyway, I can disable it and play more runs, and then enable it again to load the save to that other run whenever I feel like it. It ends up working as multiple game saves for me, which I like.

**Comment by Hlebuw3k** [comment]
Also, nevermind about the bugged items, I think that's because of the game update after I saved that run, not because of the mod.
