### ISSUE TITLE
Won saves do not delete with cloud save on

### ISSUE THREAD

**Issue by TwinGalaxy** [KingEnderBrine/-RoR2-ProperSave#64]
I'm not sure how much of an issue this really is, but when you win a run with cloud saves enabled, the save will not automatically delete itself in the cloud save. This could cause bloat and eventually maybe even fill all the cloud save storage with nothing but your won runs saves. Sure, it would take a while, but I imagine it isn't an intended effect to have each won run bloat your cloud storage just a little bit more, especially since I cannot delete the files myself as steam will just re-download them.

**Comment by KingEnderBrine** [comment]
There is only one save per profile, if you start a run and there is already a save file, it will be overwritten, so they won't take all the place in the cloud, but I will look into why they don't clean up.

**Comment by KingEnderBrine** [comment]
Should now be fixed
