### ISSUE TITLE
DBZ character saves are missing data

### ISSUE THREAD

**Issue by AndrewCloss** [KingEnderBrine/-RoR2-ProperSave#65]
The 3 mods by [Kinggrinyov ](https://thunderstore.io/package/kinggrinyov/) ([Goku](https://thunderstore.io/package/kinggrinyov/Goku/), [Vegeta ](https://thunderstore.io/package/kinggrinyov/Vegeta/), [Trunks](https://thunderstore.io/package/kinggrinyov/Trunks/)) have an additional stat, Ki/Mastery levels, which is not included in the saved data. This stat is critical to the function of these popular characters.

**Comment by KingEnderBrine** [comment]
The mod doesn't support modded characters if they have extra information that persists between stages. There API for them to add ProperSave support. But I won't do it myself.

**Comment by AndrewCloss** [comment]
@KingEnderBrine I'm trying to implement this myself but I get a silent error here, how do I correctly interact with `ProperSave.SaveFile.OnGatherSaveData.add`? Thanks.

```
ProperSave.SaveFile.OnGatherSaveData += (x) =>
{
    x.Add("PowerLevel", new { NS_KingModUtilities.PowerLevelHandler.s_currentPowerLevel });
};
```

**Comment by AndrewCloss** [comment]
That was the correct way I believe, it's being tracked in the JSON. Clicking "Load" button is the source of the silent error, producing only:

>[Info   :Proper Save] Already loading

JSON entry has:

>md":{"PowerLevel":{"ot":"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","v":"100"}}
