### ISSUE TITLE
Friend Inventory disappears on load

### ISSUE THREAD

**Issue by Solnzxe** [KingEnderBrine/-RoR2-ProperSave#66]
Hello!

Before ROR2 1.3.1 version mod worked well, but now i cant loading run because my friend is losing everything. Equip item also lost

**Comment by TheOppaiDragon** [comment]
Confirm this, same for my friend when i load a game me have all equipment, my friend lost everything

**Comment by KingEnderBrine** [comment]
Should now be fixed
