### ISSUE TITLE
Equip item vanishes upon loading the save

### ISSUE THREAD

**Issue by xChillax** [KingEnderBrine/-RoR2-ProperSave#67]
Running on the latest version of the game and the equip item just vanishes upon loading the save.

Everything else works fine however.

**Comment by alexjoi** [comment]
Same problem as with resetting statistics

**Comment by KingEnderBrine** [comment]
Should now be fixed

**Comment by xChillax** [comment]
Thanks a lot! I appreciate the effort you put into this. :)
