### ISSUE TITLE
Items Multiplied While Using Mod Characters

### ISSUE THREAD

**Issue by Thunderer1101** [KingEnderBrine/-RoR2-ProperSave#7]
I am using StartingItemsGUI, Goku and ProperSave mods for risk of rain 2
Every time I play as goku and load my game, my items are multiplied by the formula:

Amount of Items in Stage 1 * Stage no.

Example if I had 10 Syinge in stage 1 and saved and loaded stage 2 I would have 20, and stage 3 I would have 30 and so on...

Please fix this it is a very useful mod
P.S. I have not tried this with the normal characters

**Comment by KingEnderBrine** [comment]
@Thunderer1101 Hello.
> ...my items are multiplied by the formula:
> Amount of Items in Stage 1 * Stage no.
Actually items just added every time you load the game. This is because there is no difference between the new and loaded run, so StartingItemsGUI adds items.
I will add support for StartingItemsGUI when I have time.

**Comment by KingEnderBrine** [comment]
@Thunderer1101 I have added StartingItemsGUI support by disabling items adding while loading the game. The rest of this mod should work as before.
