### ISSUE TITLE
[Bug] Ridiculous equipment cooldown after save load.

### ISSUE THREAD

**Issue by g0shu** [KingEnderBrine/-RoR2-ProperSave#70]
![image](https://github.com/user-attachments/assets/ae1146ca-b37d-4274-aa6c-9a75862badb1)

**Comment by g0shu** [comment]
Reproduced on a clean profile with no other mods: https://i.imgur.com/fzpxWED.mp4

**Comment by KingEnderBrine** [comment]
Should be fixed now
