### ISSUE TITLE
Loading save doesn't load Prayer Beads bonuses

### ISSUE THREAD

**Issue by jarren-meep** [KingEnderBrine/-RoR2-ProperSave#73]
As the title states, am on an eclipse run where I printed 7 prayer beads over and over again (feeding it into the same printer) on stage 3, for about 10 minutes, and my HP was at 3k.

Just after getting into stage 9 the next day to resume the run, my HP was lowered to 1.6k, is this a Prayer Beads bug or a Mod's bug?

The save file in question:
[2c003e7d-ac94-487d-bfcc-247fdd87af40.json](https://github.com/user-attachments/files/17027845/2c003e7d-ac94-487d-bfcc-247fdd87af40.json)

**Comment by nomn-995** [comment]
same issue happened to me on a 2 player engi run also i think this happens for infusion and other (if there are any other) stat boosting items that have requirements

**Comment by KingEnderBrine** [comment]
Infusion always worked, and there aren't any other (vanilla) items like that. Now should be fixed.
