### ISSUE TITLE
Unexpected low difficulty scaling on stage 4 after loading save

### ISSUE THREAD

**Issue by WMSkyfall** [KingEnderBrine/-RoR2-ProperSave#75]
The attached game (Sundered Grove) was saved at the beginning of stage 4, after 30 minutes, by pressing ESC and selecting "Quit to Desktop". The previous stage was the post stage-3 Bazaar. I have not tried to reproduce this issue.

The legendary chest on Sundered Grove only costs $625 to open, where my expected value would be of $3000-6000. Also, at 30 minutes on Monsoon I would expect to see at least one boss-tier enemy or some Greater Wisps when the stage begins; instead I'm seeing solitary Jellyfish, Larva, Mini Mushrums, and Stone Golems. The spawn rate of new enemies also feels reduced from what I would expect at 30 minutes on Monsoon stage 4.

My list of active mods is below. I loaded the save again with "EliteCostFix" disabled; the solitary enemies that spawned were elite instead of standard, but the number of enemies and cost of the legendary chest was unchanged.

## Active Mods ##

ProperSave v2.11.1
LookingGlass v1.9.6
EmptyChestsBeGone v1.1.1
Damage Log v1.2.2
EliteCostFix v1.0.1

## Mod Dependency Stack ##

r2modman 3.1.50
BepInEx_GUI v3.0.3
BepInExPack v5.4.2117
HookGenPatcher v1.2.5
Risk_Of_Options v2.8.2

Save:
[c1b156f4-6b09-44b6-b294-6b8bac527aaf.json](https://github.com/user-attachments/files/17120195/c1b156f4-6b09-44b6-b294-6b8bac527aaf.json)

**Comment by KingEnderBrine** [comment]
Something else is wrong. I loaded your save and the chest costs 5860. Can't help you without a log, it would surely have some errors for that behavior, but the question is would you be able to reproduce it.
