### ISSUE TITLE
ProperSave different save slots? (More in comments)

### ISSUE THREAD

**Issue by SpenHub** [KingEnderBrine/-RoR2-ProperSave#77]
Does ProperSave differentiate a save-game from a multiplayer run with a friend vs a solo run? If i have a multi run saved, can I do a solo run and not affect the other save? (Is it only overwritten if I try and save before death?) I want to play a solo run but not jeopardize a multi save I already have with a friend on my machine. Thanks! <3 I love your mod so much.

**Comment by KingEnderBrine** [comment]
Yes, there is a save for each combination of players, so you can play multiplayer and singleplayer without loosing saves.
