### ISSUE TITLE
New update breaks ProperSave

### ISSUE THREAD

**Issue by theoneandonlyboogel** [KingEnderBrine/-RoR2-ProperSave#81]
It loads a run properly, but after you get to stage 2, ROR2 plays the music of the next stage but displays a black screen. I'm assuming this is ProperSave due to the console errors you get when this happens.

Console log (it repeats over and over):

[Error  : Unity Log] Duplicate instance of singleton class Stage. Only one should exist at a time.                      [Error  : Unity Log] MissingFieldException: Field not found: int RoR2.CharacterMaster.numberOfBeadStatsGained Due to: Could not find field in class                                                                                             Stack trace:                                                                                                            ProperSave.SaveData.PlayerData..ctor (RoR2.PlayerCharacterMasterController player, ProperSave.LostNetworkUser lostNetworkUser) (at <ae2336cc5d094f9f8ac60721edecfff6>:IL_0065)                                                                  ProperSave.SaveFile..ctor () (at <ae2336cc5d094f9f8ac60721edecfff6>:IL_0075)                                            ProperSave.Saving.SaveGame () (at <ae2336cc5d094f9f8ac60721edecfff6>:IL_0000)                                           ProperSave.Saving.StageOnStageStartGlobal (On.RoR2.Run+orig_BeginStage orig, RoR2.Run self) (at <ae2336cc5d094f9f8ac60721edecfff6>:IL_0031)                                                                                                     (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.Run::BeginStage>?-173040028(RoR2.Run)          RoR2.Run.OnServerSceneChanged (System.String sceneName) (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_0015)                 RoR2.Networking.NetworkManagerSystem.OnServerSceneChanged (System.String sceneName) (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_0018)                                                                                                             UnityEngine.Networking.NetworkManager.FinishLoadScene () (at <563a2666cfa24e93924d1d54d51a0b35>:IL_0047)                UnityEngine.Networking.NetworkManager.UpdateScene () (at <563a2666cfa24e93924d1d54d51a0b35>:IL_004A)                    UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at <563a2666cfa24e93924d1d54d51a0b35>:IL_000A)              UnityEngine.Networking.NetworkCallbacks.LateUpdate () (at <563a2666cfa24e93924d1d54d51a0b35>:IL_0000)

**Comment by KingEnderBrine** [comment]
Should be fixed now
