### ISSUE TITLE
Can't start when using controller

### ISSUE THREAD

**Issue by malenrick** [KingEnderBrine/-RoR2-ProperSave#9]
When entering the character select screen in singleplayer by using a ps4 controller, the menu glitches, no characters other then the Commando can be selected and attempting to start the game by pressing Square or clicking "Begin" doesn't work.

Artifact and Difficulty select is also broken when doing this.
![RoR2 Save Bug](https://user-images.githubusercontent.com/39891376/84731868-34789a00-af68-11ea-983b-844963d47a77.PNG)

If you enter Singleplayer using the mouse, the menu works just fine, with or without a controller.

**Comment by KingEnderBrine** [comment]
Hello, I know about that issue, I will fix it when I have time.

**Comment by KingEnderBrine** [comment]
Fixed it. The update is out.
